//! Helpers for compiling Angular's i18n (`i18n` attribute, `$localize`, ICU)
//! into Ivy runtime instructions.
//!
//! Angular's i18n pipeline represents translatable messages as
//! `$localize`-tagged template literals. At compile time the template's
//! translatable elements are lowered into:
//!
//! 1. A consts-array entry containing the `$localize` message (optionally
//!    prefixed by `:meaning|description@@id:` metadata).
//! 2. Creation-block instructions (`ɵɵi18n`, `ɵɵi18nAttributes`) that bind
//!    the message to an element or attribute.
//! 3. Update-block instructions (`ɵɵi18nExp`, `ɵɵi18nApply`) that feed
//!    interpolation values into the message at change-detection time.
//!
//! The helpers here produce the const-array expression and placeholder list;
//! the caller wires the returned pieces into the codegen state.

use crate::ast::{I18nMeta, InterpolationNode, TemplateNode, TextNode};

/// A compiled i18n message ready to be registered in the consts array.
#[derive(Debug, Clone)]
pub(crate) struct CompiledI18nMessage {
    /// The `$localize\`...\`` tagged template literal, as source text.
    pub localize_expr: String,
    /// The ordered interpolation expressions the runtime must evaluate —
    /// one `ɵɵi18nExp` call per entry, in order, followed by a single
    /// `ɵɵi18nApply`.
    #[allow(dead_code)]
    pub interpolations: Vec<String>,
}

/// A translatable message discovered while walking a template AST.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ExtractedI18nMessage {
    /// Optional explicit `@@id` (autogenerated when missing).
    pub id: Option<String>,
    /// Translator meaning hint.
    pub meaning: Option<String>,
    /// Translator description hint.
    pub description: Option<String>,
    /// Source text including any `${...}:NAME:` placeholder markers.
    pub source: String,
}

/// Build the translator-visible metadata prefix (`meaning|description@@id`).
/// Returns an empty string when all metadata fields are `None`.
fn format_meta(meta: &I18nMeta) -> String {
    let mut out = String::new();
    let has_head = meta.meaning.is_some() || meta.description.is_some();
    if let Some(m) = &meta.meaning {
        out.push_str(&escape_meta_segment(m));
    }
    if has_head && (meta.description.is_some() || meta.meaning.is_some()) {
        // Always emit the `|` separator when any head segment is present so
        // translators see the pipe even if only one side is supplied — the
        // same shape Angular's compiler produces.
        if meta.description.is_some() || meta.meaning.is_some() {
            out.push('|');
        }
    }
    if let Some(d) = &meta.description {
        out.push_str(&escape_meta_segment(d));
    }
    if let Some(id) = &meta.id {
        out.push_str("@@");
        out.push_str(&escape_meta_segment(id));
    }
    out
}

/// Escape a metadata segment so the `:` delimiter at the end of the prefix
/// remains unambiguous.
fn escape_meta_segment(raw: &str) -> String {
    raw.replace(':', "\\:")
}

/// Escape a char inside a JS template literal body.
fn escape_template_char(c: char, out: &mut String) {
    match c {
        '`' => out.push_str("\\`"),
        '\\' => out.push_str("\\\\"),
        '$' => out.push_str("\\$"),
        _ => out.push(c),
    }
}

/// Append an escaped literal text run to a template literal body.
fn append_template_text(body: &mut String, text: &str) {
    for c in text.chars() {
        escape_template_char(c, body);
    }
}

/// Build a `$localize` tagged template literal from a sequence of
/// translatable children and (optional) metadata.
///
/// Interpolations become placeholder expressions of the form
/// `${"\u{FFFD}N\u{FFFD}"}:INTERPOLATION:` — Angular's runtime format, where
/// `\u{FFFD}N\u{FFFD}` is the ordinal placeholder index. The raw
/// interpolation expressions are returned so the caller can emit
/// `ɵɵi18nExp` / `ɵɵi18nApply` in the update block.
pub(crate) fn compile_message(children: &[TemplateNode], meta: &I18nMeta) -> CompiledI18nMessage {
    let mut body = String::new();
    let meta_prefix = format_meta(meta);
    if !meta_prefix.is_empty() {
        body.push(':');
        body.push_str(&meta_prefix);
        body.push(':');
    }
    let mut interpolations: Vec<String> = Vec::new();
    walk_children(children, &mut body, &mut interpolations);
    CompiledI18nMessage {
        localize_expr: format!("$localize`{}`", body),
        interpolations,
    }
}

fn walk_children(children: &[TemplateNode], body: &mut String, interpolations: &mut Vec<String>) {
    for child in children {
        match child {
            TemplateNode::Text(TextNode { value }) => {
                append_template_text(body, value);
            }
            TemplateNode::Interpolation(InterpolationNode { expression, .. }) => {
                let idx = interpolations.len();
                interpolations.push(expression.clone());
                body.push_str(&format!(
                    "${{\"\\u{{FFFD}}{idx}\\u{{FFFD}}\"}}:INTERPOLATION:"
                ));
            }
            TemplateNode::Element(el) => {
                // Nested tag: emit a placeholder around its contents so the
                // translation can reposition or preserve formatting markup.
                // The runtime links this to the actual DOM via the template;
                // at extraction time the tag appears as `{$START_TAG_FOO}`.
                let tag_upper = el.tag.to_ascii_uppercase().replace('-', "_");
                body.push_str(&format!(
                    "${{\"\\u{{FFFD}}#{idx}\\u{{FFFD}}\"}}:START_TAG_{tag_upper}:",
                    idx = interpolations.len()
                ));
                interpolations.push(format!("/* element {} */", el.tag));
                walk_children(&el.children, body, interpolations);
                body.push_str(&format!(
                    "${{\"\\u{{FFFD}}/#{idx}\\u{{FFFD}}\"}}:CLOSE_TAG_{tag_upper}:",
                    idx = interpolations.len() - 1
                ));
            }
            TemplateNode::IcuExpression(icu) => {
                // Angular's runtime ICU parser (`ICU_BLOCK_REGEXP` in
                // `@angular/core`'s `i18n_parse`) matches the switch position
                // against `\uFFFD<idx>:?\d*\uFFFD` — the same indexed
                // placeholder marker used for regular interpolations. The
                // translator-facing placeholder name (`VAR_PLURAL`,
                // `VAR_SELECT`, `VAR_SELECTORDINAL`) is carried as the
                // `${...}:NAME:` block label, which `$localize` strips when
                // building the runtime message. Pushing the user-authored
                // switch expression into `interpolations` makes the caller
                // emit the matching `ɵɵi18nExp(ctx.<expr>)` in the update
                // block.
                let idx = interpolations.len();
                interpolations.push(icu.switch_expression.clone());
                let (placeholder_name, category_kw) = match icu.category {
                    crate::ast::IcuCategory::Plural => ("VAR_PLURAL", "plural"),
                    crate::ast::IcuCategory::Select => ("VAR_SELECT", "select"),
                    crate::ast::IcuCategory::SelectOrdinal => {
                        ("VAR_SELECTORDINAL", "selectordinal")
                    }
                };
                body.push('{');
                body.push_str(&format!(
                    "${{\"\\u{{FFFD}}{idx}\\u{{FFFD}}\"}}:{placeholder_name}:"
                ));
                body.push_str(", ");
                body.push_str(category_kw);
                body.push_str(", ");
                for case in &icu.cases {
                    append_template_text(body, &case.key);
                    body.push_str(" {");
                    append_template_text(body, &case.body);
                    body.push_str("} ");
                }
                body.push('}');
            }
            _ => {
                // Other control-flow blocks inside an i18n region are
                // left untouched for now — a future pass can expand `@if`
                // /`@for` children into their own sub-messages.
            }
        }
    }
}

/// Build a `$localize` message for a single static attribute value.
/// The attribute carries no interpolations at this point; interpolation
/// inside `i18n-<attr>` bindings will be added alongside property-binding
/// support in a later iteration.
pub(crate) fn compile_attribute_message(value: &str, meta: &I18nMeta) -> CompiledI18nMessage {
    let mut body = String::new();
    let meta_prefix = format_meta(meta);
    if !meta_prefix.is_empty() {
        body.push(':');
        body.push_str(&meta_prefix);
        body.push(':');
    }
    append_template_text(&mut body, value);
    CompiledI18nMessage {
        localize_expr: format!("$localize`{}`", body),
        interpolations: Vec::new(),
    }
}

/// Walk a parsed template, collecting every translatable message reachable
/// from `i18n` element attributes and `i18n-<attr>` markers.
///
/// Each `i18n` element produces one message containing the element's text
/// children (with interpolations replaced by `{$INTERPOLATION}` markers and
/// nested ICU expressions inlined). Each `i18n-<attr>` marker produces one
/// message containing the paired static attribute's value.
pub fn extract_messages(nodes: &[TemplateNode]) -> Vec<ExtractedI18nMessage> {
    let mut out = Vec::new();
    walk_for_extraction(nodes, &mut out);
    out
}

fn walk_for_extraction(nodes: &[TemplateNode], out: &mut Vec<ExtractedI18nMessage>) {
    for node in nodes {
        match node {
            TemplateNode::Element(el) => {
                let mut i18n_meta: Option<I18nMeta> = None;
                let mut attr_messages: Vec<(String, I18nMeta)> = Vec::new();
                for a in &el.attributes {
                    match a {
                        crate::ast::TemplateAttribute::I18n(m) => i18n_meta = Some(m.clone()),
                        crate::ast::TemplateAttribute::I18nAttr { target, meta } => {
                            attr_messages.push((target.clone(), meta.clone()));
                        }
                        _ => {}
                    }
                }
                if let Some(meta) = i18n_meta {
                    let source = render_extraction_text(&el.children);
                    out.push(ExtractedI18nMessage {
                        id: meta.id,
                        meaning: meta.meaning,
                        description: meta.description,
                        source,
                    });
                }
                for (target, meta) in attr_messages {
                    let value = el
                        .attributes
                        .iter()
                        .find_map(|a| match a {
                            crate::ast::TemplateAttribute::Static { name, value }
                                if name == &target =>
                            {
                                Some(value.clone().unwrap_or_default())
                            }
                            _ => None,
                        })
                        .unwrap_or_default();
                    out.push(ExtractedI18nMessage {
                        id: meta.id,
                        meaning: meta.meaning,
                        description: meta.description,
                        source: value,
                    });
                }
                walk_for_extraction(&el.children, out);
            }
            TemplateNode::IfBlock(b) => {
                walk_for_extraction(&b.children, out);
                for branch in &b.else_if_branches {
                    walk_for_extraction(&branch.children, out);
                }
                if let Some(else_c) = &b.else_branch {
                    walk_for_extraction(else_c, out);
                }
            }
            TemplateNode::ForBlock(b) => {
                walk_for_extraction(&b.children, out);
                if let Some(empty) = &b.empty_children {
                    walk_for_extraction(empty, out);
                }
            }
            TemplateNode::SwitchBlock(b) => {
                for c in &b.cases {
                    walk_for_extraction(&c.children, out);
                }
                if let Some(d) = &b.default_branch {
                    walk_for_extraction(d, out);
                }
            }
            TemplateNode::DeferBlock(b) => {
                walk_for_extraction(&b.children, out);
                if let Some(p) = &b.placeholder {
                    walk_for_extraction(p, out);
                }
                if let Some(l) = &b.loading {
                    walk_for_extraction(l, out);
                }
                if let Some(e) = &b.error {
                    walk_for_extraction(e, out);
                }
            }
            _ => {}
        }
    }
}

/// Render a child list as the human-visible source text of an extracted
/// message. Interpolations and nested elements collapse into named
/// placeholders so the translator sees a stable surface.
fn render_extraction_text(children: &[TemplateNode]) -> String {
    let mut out = String::new();
    for child in children {
        match child {
            TemplateNode::Text(TextNode { value }) => out.push_str(value),
            TemplateNode::Interpolation(InterpolationNode { expression, .. }) => {
                out.push_str(&format!("{{{{ {expression} }}}}"));
            }
            TemplateNode::IcuExpression(icu) => {
                out.push('{');
                out.push_str(&icu.switch_expression);
                out.push_str(", ");
                out.push_str(match icu.category {
                    crate::ast::IcuCategory::Plural => "plural",
                    crate::ast::IcuCategory::Select => "select",
                    crate::ast::IcuCategory::SelectOrdinal => "selectordinal",
                });
                out.push_str(", ");
                for case in &icu.cases {
                    out.push_str(&case.key);
                    out.push_str(" {");
                    out.push_str(&case.body);
                    out.push_str("} ");
                }
                out.push('}');
            }
            TemplateNode::Element(el) => {
                let inner = render_extraction_text(&el.children);
                out.push_str(&format!("<{tag}>{inner}</{tag}>", tag = el.tag));
            }
            _ => {}
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::{InterpolationNode, TextNode};

    #[test]
    fn compiles_static_message() {
        let children = vec![TemplateNode::Text(TextNode {
            value: "Hello".to_string(),
        })];
        let msg = compile_message(&children, &I18nMeta::default());
        assert_eq!(msg.localize_expr, "$localize`Hello`");
        assert!(msg.interpolations.is_empty());
    }

    #[test]
    fn compiles_meta_prefix() {
        let children = vec![TemplateNode::Text(TextNode {
            value: "Hi".to_string(),
        })];
        let meta = I18nMeta {
            id: Some("intro".to_string()),
            meaning: Some("greeting".to_string()),
            description: Some("welcome".to_string()),
        };
        let msg = compile_message(&children, &meta);
        assert_eq!(msg.localize_expr, "$localize`:greeting|welcome@@intro:Hi`");
    }

    #[test]
    fn compiles_interpolation_placeholders() {
        let children = vec![
            TemplateNode::Text(TextNode {
                value: "Hello, ".to_string(),
            }),
            TemplateNode::Interpolation(InterpolationNode {
                expression: "name".to_string(),
                pipes: Vec::new(),
            }),
            TemplateNode::Text(TextNode {
                value: "!".to_string(),
            }),
        ];
        let msg = compile_message(&children, &I18nMeta::default());
        assert_eq!(msg.interpolations, vec!["name".to_string()]);
        assert!(msg.localize_expr.contains(":INTERPOLATION:"));
        assert!(msg.localize_expr.contains("\\u{FFFD}0\\u{FFFD}"));
    }

    #[test]
    fn escapes_template_backticks() {
        let children = vec![TemplateNode::Text(TextNode {
            value: "a`b$c\\d".to_string(),
        })];
        let msg = compile_message(&children, &I18nMeta::default());
        assert!(msg.localize_expr.contains("a\\`b\\$c\\\\d"));
    }

    #[test]
    fn compiles_attribute_message() {
        let meta = I18nMeta {
            id: Some("tip".to_string()),
            ..Default::default()
        };
        let msg = compile_attribute_message("Tooltip", &meta);
        assert_eq!(msg.localize_expr, "$localize`:@@tip:Tooltip`");
    }

    #[test]
    fn extracts_messages_from_template() {
        use crate::ast::{ElementNode, TemplateAttribute};
        let nodes = vec![TemplateNode::Element(ElementNode {
            tag: "h1".to_string(),
            attributes: vec![TemplateAttribute::I18n(I18nMeta {
                id: Some("intro".to_string()),
                description: Some("welcome".to_string()),
                meaning: None,
            })],
            children: vec![TemplateNode::Text(TextNode {
                value: "Hello".to_string(),
            })],
            is_void: false,
        })];
        let messages = extract_messages(&nodes);
        assert_eq!(messages.len(), 1);
        assert_eq!(messages[0].id.as_deref(), Some("intro"));
        assert_eq!(messages[0].source, "Hello");
        assert_eq!(messages[0].description.as_deref(), Some("welcome"));
    }

    #[test]
    fn extracts_messages_from_i18n_attr() {
        use crate::ast::{ElementNode, TemplateAttribute};
        let nodes = vec![TemplateNode::Element(ElementNode {
            tag: "img".to_string(),
            attributes: vec![
                TemplateAttribute::Static {
                    name: "alt".to_string(),
                    value: Some("Hi".to_string()),
                },
                TemplateAttribute::I18nAttr {
                    target: "alt".to_string(),
                    meta: I18nMeta {
                        id: Some("alt-id".to_string()),
                        ..Default::default()
                    },
                },
            ],
            children: Vec::new(),
            is_void: true,
        })];
        let messages = extract_messages(&nodes);
        assert_eq!(messages.len(), 1);
        assert_eq!(messages[0].id.as_deref(), Some("alt-id"));
        assert_eq!(messages[0].source, "Hi");
    }
}
